development:
  host: localhost
  database: cat

test:
  host: localhost
  database: cat_test

# set these environment variables on your prod server
production:
  host: 127.0.0.1
  database: cat
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
